// import 'package:flutter/material.dart';
// const Color backgroundColor1 = Color(0xffebecf1);
// const Color backgroundColor2 = Color(0xfff7f7f7);
// const Color buttonBlack = Color(0xff303030);
// const Color colorRed = Colors.red;
// const Color trafficOrange = Color(0xffe72f22);
// const Color backgroundColor3 = Color(0xffebebf0);
// const Color redAlt1 = Color(0xffff4057);
// const Color redAlt2 = Color(0xfffe645c);
// const Color blackAlt1 = Color(0xff0b0321);
// const Color cream = Color(0xfffcdde0);
// const Color cream2 = Color(0xfff8bac1);
// const Color whiteAlt = Color(0xfff3f4f9);
// const Color whiteAlt2 = Color(0xfff3f5fa);
// const Color blackKy = Color(0xff000000);
// const Color browNy = Color(0xff644C42);